### ISSUE TITLE
error PostCSS plugin postcss-100vh-fix requires PostCSS 8

### ISSUE THREAD

**Issue by DonHuskini** [postcss/postcss-100vh-fix#8]
I'm getting the error `PostCSS plugin postcss-100vh-fix requires PostCSS 8` when starting the dev server with Parcel 2:

The packages are these:
"postcss": "^8.3.6",
"postcss-100vh-fix": "^1.0.2",
"parcel": "^2.0.0-nightly.790"

Anyone with the same problem?

**Comment by Ali-Javanmardi** [comment]
I have same problem as due to compatibility with vue.js 3 I installed tailwindcss with postcss7.0 compat

now this plugin requires postcss8

I hope there is a postcss7 compatible version

**Comment by DonHuskini** [comment]
I ended up going with another solution that doesn't require the plugin. Get the height from the window.innerHeight. It will not count the bottom nav bar height.

**Comment by Ali-Javanmardi** [comment]
Great, I did the same and got correct result on my android chrome.
I hope it works for all versions
